version: 2
updates:
  # Configuration for npm dependencies
  - package-ecosystem: "npm"
    directory: "/" # Location of package.json
    schedule:
      interval: "weekly" # Options: daily, weekly, monthly

  # Configuration for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Search for workflows in the root
    schedule:
      interval: "weekly"

