services:
  donbot:
    image: ghcr.io/vikraman/donbot:latest
    container_name: donbot
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis
    labels:
      - com.centurylinklabs.watchtower.enable=true

  redis:
    image: redis:7-alpine
    container_name: donbot-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --appendonly yes

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup --label-enable

volumes:
  redis-data:
